name: release-installer
'on':
  release:
    types:
      - published

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - uses: ./.github/run-tests

      - name: Upload Release Asset DXRando
        id: upload-release-asset-dxrando
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: installer/dist/DXRandoInstaller.exe
          asset_name: DXRandoInstaller.exe
          tag: ${{ github.ref }}

      - name: Upload Release Asset BingoViewer
        id: upload-release-asset-bingoviewer
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: installer/dist/BingoViewer.exe
          asset_name: BingoViewer.exe
          tag: ${{ github.ref }}

  linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - run: sudo apt-get update -y
      - run: sudo apt-get install -y python3-tk idle3 binutils

      - uses: ./.github/run-tests

      - name: Upload Release Asset DXRando
        id: upload-release-asset-dxrando
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: installer/dist/DXRandoInstaller
          asset_name: DXRandoInstaller-Linux
          tag: ${{ github.ref }}

      - name: Upload Release Asset BingoViewer
        id: upload-release-asset-bingoviewer
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: installer/dist/BingoViewer
          asset_name: BingoViewer-Linux
          tag: ${{ github.ref }}
